clear 
clc
close all
figure
load('test1.mat')
plot3(result.fix_res(1).X(1,:),result.fix_res(1).X(2,:) ,...
    result.fix_res(1).X(3,:),'b-.','linewidth',2);
hold on
plot3(result.fix_res(2).X(1,:),...
    result.fix_res(2).X(2,:) , ...
    result.fix_res(2).X(3,:),'r','linewidth',2);
hold on
plot3(result.fix_res(1).X(1,1),result.fix_res(1).X(2,1) ,...
    result.fix_res(1).X(3,1),'p','HandleVisibility','off');
hold on
plot3(result.fix_res(2).X(1,1),...
    result.fix_res(2).X(2,1), ...
    result.fix_res(2).X(3,1),'o','HandleVisibility','off');
hold on

load('test2.mat')
plot3(result.fix_res(1).X(1,:),result.fix_res(1).X(2,:) ,...
    result.fix_res(1).X(3,:),'b-.','linewidth',2);
hold on
plot3(result.fix_res(2).X(1,:),...
    result.fix_res(2).X(2,:) , ...
    result.fix_res(2).X(3,:),'r','linewidth',2);
hold on
plot3(result.fix_res(1).X(1,1),result.fix_res(1).X(2,1) ,...
    result.fix_res(1).X(3,1),'p','HandleVisibility','off');
hold on
plot3(result.fix_res(2).X(1,1),...
    result.fix_res(2).X(2,1), ...
    result.fix_res(2).X(3,1),'o','HandleVisibility','off');
hold on

load('test3.mat')
plot3(result.fix_res(1).X(1,:),result.fix_res(1).X(2,:) ,...
    result.fix_res(1).X(3,:),'b-.','linewidth',2);
hold on
plot3(result.fix_res(2).X(1,:),...
    result.fix_res(2).X(2,:) , ...
    result.fix_res(2).X(3,:),'r','linewidth',2);
hold on
plot3(result.fix_res(1).X(1,1),result.fix_res(1).X(2,1) ,...
    result.fix_res(1).X(3,1),'p');
hold on
plot3(result.fix_res(2).X(1,1),...
    result.fix_res(2).X(2,1), ...
    result.fix_res(2).X(3,1),'o');
hold on
legend('目标1','追踪航天器1',...
    '目标2','追踪航天器2',...
    '目标3','追踪航天器3','目标起始点','追踪航天器起始点')
set(gca,'FontSize',14)

box on
grid on
xlabel('x(km）');
ylabel('y(km）');
zlabel('z(km）');
box on
